package lejos.nxt;

/**
 * Error generated by the Flash class
 */
public class FlashError extends Error
{
	public FlashError() {
		super();
	}

	public FlashError(String message) {
		super(message);
	}

}
